@input(['name' => 'name', 'label' => __('zone::province.name')])
@input(['name' => 'code', 'label' => __('zone::province.code')])
@input(['name' => 'sort_order', 'label' => __('zone::province.sort_order')])
@input(['name' => 'zip_code', 'label' => __('zone::province.zip_code')])
@checkbox(['name' => 'status', 'label' => '', 'placeholder' => __('zone::province.status')])
